name: reza_reservation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  get: any
  google_fonts: ^5.1.0
  intl: 0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: 1.1.0
  file_picker: 6.2.0
  cached_network_image: 3.3.1
  dio: 5.4.1
  focus_detector_v2: 3.1.0+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

